import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const myFont = Inter({
  weight: ["200", "400"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hystoria",
  description: "Generated by muhammad ismed novian",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${myFont.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
